[build]
target = "index.html"
dist = "dist"
cargo = false
release = true
filehash = false
no_sri = true
# public-url = "/"
minify = "never"

[serve]
addresses = ["0.0.0.0"]
port = 8080
open = false
disable_sri = true

[watch]
watch = []
ignore = []

[serve.headers]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[copy]
source = "static"
destination = "static"

[build.files]
"static/sqlite.org/sqlite3.js" = "static/sqlite.org/sqlite3.js"
"static/sqlite.org/sqlite3-worker1.js" = "static/sqlite.org/sqlite3-worker1.js"
"static/sqlite.org/sqlite3.wasm" = "static/sqlite.org/sqlite3.wasm"
"static/sqlite.org/sqlite3-opfs-async-proxy.js" = "static/sqlite.org/sqlite3-opfs-async-proxy.js"


